### PR TITLE
UI: Enhancement (#1033)

### PR DESCRIPTION
**Pull request by Map1en**
- issue #1033

----------------------------------------------------------------
> 0570716

Fixed the following issues:
1. Main Item: User Dialog Box
   - Adjust the height of the text in the tags to be centered.
   - Change the background color of the counter when hovering over VRC notes.
   - Re-align the radiogroup and refresh button for model creation, and also re-align the top of the created worlds and groups.

2. Avatar Dialog Box
   - Leave a space below the local notes.

3. Main Screen
   - Align the input boxes on each page with the sidebar friend list.
   - Avoid using both `v-if` and `v-show` simultaneously; remove conflicts.

4. Search Avatar Page
   - Re-align the buttons and radio at the top.

5. Settings
   - Re-align and adjust the VRC configuration page.
   - Re-align and adjust the data backup page.
   - Adjust the spacing of the notification filters.

--------------------------------------------------
> cdf5688193baa29c31547541c407aa7bb9b6a1d3
cb22cd0c24e52e66c971ba3726f5896c2ea30f14

Fixed the following issues:
1. Background color issue when hovering over input count in non-default themes
2. Adjusted the top height of the feed page
3. Fixed margin issues for detailed information when status changes in the feed page

--------------------------------------------------
> 3cce05c

Fixed the following issues:
1. Feed Page
   - Fixed spacing between status items

2. Favorites Page
   - Search and Sort UI
     • Reorganized search box and sorting methods to top-right corner
     • Replaced Switch with RadioGroup for sorting methods (as they represent distinct values, not binary states)
     • Similar components will be updated in future PRs
   - Visual Improvements
     • Restored original colors for friend avatars (removed grey tint, Because it is inconsistent with the behavior of the friends status bar on the right side.)
     • Offline status icons updates pending further consideration
   - Data Display
     • Added "No data" placeholder in empty Collapse components
     • Replaced dot indicators with tags for status of world favorites (It can easily cause confusion, we switched to using tags to improve recognition.)
   - Import/Export Dialog Features
     • Redesigned import dialog layouts across all three tabs
     • Enhanced export dialogs:
       - Added click-to-copy functionality for textarea content
       - Implemented success/failed notifications
   - UI Polish
     • Adjusted text case displays for consistency
     • Basic theme compatibility improvements
       (Note: Comprehensive theme adjustments pending due to color hierarchy complexity)

----------------------------------------------------------------------------------------------------
> 20964f7

_I'm sorry for making such fragmented commits and not following the specific pages._

Fixed the following issues:

1. Corrected switch alignment on the "Show starred friends only" page

2. Fixed tag alignment for the world group visibility status in favorites

3. Adjusted switch alignment in the top-right corner of the favorites page model editor

4. Added red color to the logout button for better visibility and user recognition

5. Improved user experience by highlighting save buttons:
   - Notification Filter save button
   - Wrist Feed Filters save button

-----------------------------------------------------------------------------------------------------
> fb45546

Fixed the following issues:

1. Replaced the switches for non-binary attributes with radio groups on the settings page.

2. Refined the switch component and adjusted its styling. 
   - Regarding this component, due to the complexity of Pug's mixins, not all cases can be replaced. Therefore, there are still some alignment issues with long text. I will look into how to encapsulate everything in the future for easier unified modification.

4. Unified the icons for the notification messages to "info."

### CODE REVIEW

**Comment by Natsumi-sama** [comment]
Those `v-if`s on the pages were on purpose to unload all those DOM elements when they aren't needed, for example if you have a large amount of local favorites even with `display: none;` the page can cause massive program wide slowdowns even when the page isn't in view. Maybe there are better ways to go about this but at least this was my thought process when I added those to all the pages.

**Comment by Natsumi-sama** [comment]
`.x-friend-item:hover .el-input__count` will also need to be adjusted for dark theme, and probably every other theme as well (pain).
These are some nice much needed CSS polishes though.

**Comment by Map1en** [comment]
This PR has become somewhat disorganized and the content is not well-structured. In the future, I will submit PRs separately for each component.

**Comment by Map1en** [comment]
> Those `v-if`s on the pages were on purpose to unload all those DOM elements when they aren't needed, for example if you have a large amount of local favorites even with `display: none;` the page can cause massive program wide slowdowns even when the page isn't in view. Maybe there are better ways to go about this but at least this was my thought process when I added those to all the pages.

This issue can be resolved by using v-if to control the entire tag. If you think generating and unloading the entire page might be problematic, you can also use v-if or clear data in performance-sensitive areas. For example, you can determine if the opened tag page is not the current page, and then unload the DOM. Using v-if and v-show together can lead to additional performance overhead and can be confusing, making it difficult to debug. I think this issue was mentioned in the Vue 2 documentation, but I can't remember for sure.quq

**Comment by Natsumi-sama** [comment]
I much prefer these larger PRs personally it's easy for me to manage, and not using both v-if and v-show at the same time makes sense, in most cases clearing data isn't an option due to the use of shared arrays, I think unloading UI that isn't in use is preferred, although I think some things are left loaded in on purpose for elements to keep their last state.

**Comment by Map1en** [comment]
> I much prefer these larger PRs personally it's easy for me to manage, and not using both v-if and v-show at the same time makes sense, in most cases clearing data isn't an option due to the use of shared arrays, I think unloading UI that isn't in use is preferred, although I think some things are left loaded in on purpose for elements to keep their last state.

In performance-sensitive element, can use **keep-alive** to retain the instance without destroying it, preserving the state while only adding the DOM. However, this requires splitting into smaller components. For performance-sensitive and reusable parts, this approach is worthwhile. Additionally, many areas currently share data and logic, which is not a good practice. For future optimization and easier maintenance, components should be split. For now, I am trying to only modify the UI parts, and if I encounter any logical issues, I will submit them in others PR.

**Comment by Map1en** [comment]
@Natsumi-sama 

I'm limiting this PR to these commits since I wasn't quite sure about the ideal PR size. I kept adding commits after learning that larger PRs can be more convenient for review. Looking at what's been done, I think I've managed to fix quite a few basic UI issues, particularly those alignment problems. I'd like to continue contributing more PRs to this project, though it seems there aren't many bugs or features I can work on at the moment.

If I continue with UI improvements, the next phase would involve more substantial changes - like modifying the visual presentation (though preferences can vary from person to person) and adapting to other themes (which would require considerable effort). Alternatively, there are other areas to explore, such as code splitting, performance optimization, or other improvements. However, these would involve significant changes, and while I'm interested in working on them, I'd need to get confirmation first. So I'm hoping we can discuss this further, as I'm looking forward to contributing more commits to this project.

**Comment by Natsumi-sama** [comment]
I'll start testing these commits soon so I can get them merged, please send me a DM on Discord I have plenty of things I'd like to discuss.

**Comment by slord399** [comment]
Seems to be setting toggle on Settings-Appearance page got messed up.
"Tooltips" toggle now behave opposite than intended.
(Visual and Actual not matched)

Ref. https://canary.discord.com/channels/854071236363550763/864248845301710908/1320180810850238596

**Comment by Myrkie** [comment]
this seems to have also caused issues with some settings in the material theme, example being slider buttons no longer being consistent 
image

**Comment by SalbugVR** [comment]
> Seems to be setting toggle on Settings-Appearance page got messed up. "Tooltips" toggle now behave opposite than intended. (Visual and Actual not matched)
> 
> Ref. https://canary.discord.com/channels/854071236363550763/864248845301710908/1320180810850238596

Yeah, for reference.


https://github.com/user-attachments/assets/0bc89972-e4cb-401e-8aee-6a32a73a331a

**Comment by SalbugVR** [comment]
Also wanna point out that I'm noticing a lot of text input fields with no clearly defined box boundries.

image

**Comment by Myrkie** [comment]
tag text also don't seem to be centered anymore 
image

**Pull request merged**
