### PR TITLE
refactor: convert input document to JSDoc format

### PR DESCRIPTION
**Pull request by KisaragiEffective**

### CODE REVIEW

**Comment by Natsumi-sama** [comment]
Screenshot 2023-12-03 005005

**Comment by KisaragiEffective** [comment]
@Natsumi-sama I have addressed them in b76bdc1, I did not think it was used in entire code-base 😓

**Comment by Natsumi-sama** [comment]
Hah yea it's a bit hard to tell with how insanely large this file is, thanks for this though.

**Comment by KisaragiEffective** [comment]
Could you approve workflows so we can see if they will be green?

**Pull request merged**
