### PR TITLE
Show Headset Battery in VR Overlay

### LINKED ISSUE #741: [Feature Request] Show Headset Battery in VR Overlay device list
Virtual Desktop started transmitting headset battery information to SteamVR since the recent 1.30.3 Beta. I think it would be useful if the headset battery was shown alongside the battery charge for controllers and trackers.

UI: If the user is wearing a headset with a battery, then an extra item with a headset icon would be shown in the overlay VR devices section.

This would be very useful when playing wirelessly for quickly checking your headset battery.

I am interested in doing the implementation for this if I can get some help with finding the required icons.

### PR DESCRIPTION
**Pull request by konsti219**
Fixes #741

### CODE REVIEW

**Comment by Natsumi-sama** [comment]
Commit looks really good, I'll test with my cable headset later today.

**Comment by Natsumi-sama** [comment]
It does indeed skip the headset nice, will merge with next nightly update, lemme know if there is anything else you're interesting in doing and I'll help you find what you need.

**Comment by konsti219** [comment]
I have some ideas, but I think those will take me a few days of experimentation.

**Comment by Natsumi-sama** [comment]
Well feel free to message me on Discord "NatsumiDa" with any questions or if you'd like to know if something is viable with this code base.

**Pull request merged**
