### PR TITLE
Fix Friends List Rendering and LocaleCompare Error in FriendsGroup Computed Properties

### PR DESCRIPTION
**Pull request by refiaa**
This PR addresses issue [#909](https://github.com/vrcx-team/VRCX/issues/909), which caused the friends list to fail to render and resulted in a `localeCompare` error due to invalid or missing `name` properties during sorting.

### Key Changes:
1. **compareByName Function Update**:
   - Adjusted the `compareByName` function to handle cases where `name` properties may be `undefined` or missing. Now, it safely compares strings or returns `0` for invalid data.

2. **API.getUser Error Handling**:
   - Enhanced the `API.getUser` method to ensure only valid user data is processed. If a user lacks a `name` property, the method now logs an error and avoids emitting invalid data.

3. **FriendsGroup Computed Properties Fix**:
   - Restored the `friendsGroup1`, `friendsGroup2`, and `friendsGroup3` computed properties to their original logic while ensuring proper sorting of valid data.
   - Simplified unnecessary data filtering, which was causing issues in displaying the friends list.

These changes resolve the rendering issue while ensuring that invalid data no longer disrupts the friends list display.

### CODE REVIEW

**Comment by Natsumi-sama** [comment]
already fixed here https://github.com/vrcx-team/VRCX/commit/404751763f0896e291540c59d0c51d33a1e5f3a3

**Comment by refiaa** [comment]
so sad

**Comment by Natsumi-sama** [comment]
The invalid user data is most likely deleted users that are still friends we keep them in so users can unfriend them.

**Comment by refiaa** [comment]
I appreciate your response. I will go ahead and close this PR now.

**Comment by Natsumi-sama** [comment]
Sorry about the timing I didn't expect you to fix it yourself.

**Comment by refiaa** [comment]
nevermind it!

**Pull request closed without merging**
