### PR TITLE
Repo cleanup

### PR DESCRIPTION
**Pull request by Natsumi-sama**

### CODE REVIEW

**Comment by Natsumi-sama** [comment]
Was going to merge this but noticed the github workflow change, never mind.

**Comment by DubyaDude** [comment]
I was working on redoing the action, prepping for a single repo. I can split that up rq if ya want

**Comment by Natsumi-sama** [comment]
I've already pushed a build but it would still be nice for next build.

**Comment by DubyaDude** [comment]
@Natsumi-sama action changes removed from the branch. Just be sure to give this a test run, I'm pretty sure it all works.

**Pull request merged**
