### PR TITLE
Add unlimited local avatar favs

### PR DESCRIPTION
**Pull request by Nekromateion**
Implement unlimited local avatar favs with VRC+ requirement.

### CODE REVIEW

**Comment by bornato** [comment]
wait why vrc+ requirement if it's local only and for you to change into them you gotta completely reboot the game?

**Comment by Myrkie** [comment]
> wait why vrc+ requirement if it's local database only and for you to change into them you gotta completely reboot the game?

Because making it non VRCPlus would make VRCPlus pointless thus interfering with VRChats source of income, VRChats has made it very clear in the past they don't want this to happen (such as with EMMvrc the mod for VRChat having to lock unlimited avatars behind VRCPlus ownership)

**Comment by Nekromateion** [comment]
> wait why vrc+ requirement if it's local only and for you to change into them you gotta completely reboot the game?

You don't have to restart your game to switch into the Avatars, I do not know where you got that from.

**Comment by Myrkie** [comment]
yeah for clarification changing avatar from the website or VRCX is not a VRCPlus requirement (unless vrchat changes their mind), only local favorites are locked behind owning VRCPlus for the above reasons.

**Comment by bornato** [comment]
> > wait why vrc+ requirement if it's local database only and for you to change into them you gotta completely reboot the game?
> 
> Because making it non VRCPlus would make VRCPlus pointless thus interfering with VRChats source of income, VRChats has made it very clear in the past they don't want this to happen (such as with EMMvrc the mod for VRChat having to lock unlimited avatars behind VRCPlus ownership)

i believe having it non vrc+ would make people annoyed enough for having to mess around with their favorites all the time to actively want to buy vrc+, sounds counter intuitive to me if the idea is to get people to want to buy it (considering how to get people to actively want to engage with your product)

although i guess it's also fair to just be safe enough, since the community is not responsible for how they plan out the game's finance (and we've had issues with stuff like that with the API before as well, not only on VRCX)



> > wait why vrc+ requirement if it's local only and for you to change into them you gotta completely reboot the game?
> 
> You don't have to restart your game to switch into the Avatars, I do not know where you got that from.

If you don't have to restart anymore that's new to me, I got so used to not being able I just gave up entirely on even bothering with it

**Comment by Myrkie** [comment]
> If you don't have to restart anymore that's new to me, I got so used to not being able I just gave up entirely on even bothering with it

yep the change was made 4 months ago now as apart of an open beta update before it was pushed to live

https://discord.com/channels/189511567539306508/503009489486872583/1228107514399293440
image

**Comment by extremeblackliu** [comment]
translation is wrong till latest version.
https://github.com/vrcx-team/VRCX/pull/845/files#diff-af9254c4cffd2f02ec309237af67573be0b6f9d22069aab754ee5768a678f7a8R769

to above:
this is open-source software no idea why you guys complain.

**Pull request merged**
