### PR TITLE
Add japanese localization

### PR DESCRIPTION
**Pull request by Assault1892**
add localization for ja_JP (日本語, japanese)

I have translated the text while trying to stay as faithful as possible to the original meaning, but some modifications have been made to preserve the layout and other formatting.

### CODE REVIEW

**Comment by Assault1892** [comment]
May I translate README.md into Japanese as well?
Some of my friends said that the README is hard to understand because it is in English.

**Comment by Natsumi-sama** [comment]
IMO there is nothing worth translating in the readme but if you'd like to anyway create it as `README.jp.md`

**Comment by Myrkie** [comment]
Could do it as a dropdown in the readme

<details><summary>Japanese</summary>
<p>
Like this

</p>
</details>

**Comment by Assault1892** [comment]
Is it possible to translate the README.md with a link to the Japanese version, as in other repositories?
image

**Comment by Myrkie** [comment]
> Is it possible to translate the README.md with a link to the Japanese version, as in other repositories? image

it would be probably be recommended that the Readme.MD is in the repository and the link just goes to file in the repository so it doesn't link to any external repos which could confuse users

**Comment by Natsumi-sama** [comment]
Yes by creating a `README.jp.md` it will be linked to in the main readme.

**Comment by Assault1892** [comment]
ok, tysm <3

**Pull request merged**
